### ISSUE TITLE
I line-by-line translated the C# port to java

### ISSUE THREAD

**Issue by lahwran** [husl-colors/husl#26]
complete with tests.

https://github.com/lahwran/pin/commit/9f18fadf62144dc30acf38842a5356a440923e46 (impl), and https://github.com/lahwran/pin/commit/db89dfa431464a97df7074f32745b3af397c050c (which has a bunch of other stuff too, but also tests.)

I did this because it said the java port was unfinished. Also because it was fun.

**Comment by boronine** [comment]
Amazing work. I would love to add make it official and add it to the list on the homepage! In order to do this, I need you to do one of two things:

1. Add an Open Source license (MIT preferred) to your repo
2. Copy over HUSL-related code into the empty repo I created and add an MIT license with your name in it. I sent you an invitation to the organization so you should have all the permissions. It's up to you if you want to make it public.

New repo: https://github.com/husl-colors/husl-java Let me know when you are ready and I'll do the rest.

Thanks again!

**Comment by lahwran** [comment]
+1 on use of the MIT license. I did #1, but I would prefer to also do #2. I don't have access to initialize the repo you linked, though, even though you added me to the org.

**Comment by boronine** [comment]
Ah, I needed to connect the repo with the Collaborator team. You should have access now!

**Comment by lahwran** [comment]
Hey I'm sorry, I'm probably not going to get to packaging it up nicely so it can be put in that repo. if you like, I could just dump the code there and leave it to others to either clean it up so it can be packaged, or copy it into their projects.

**Comment by boronine** [comment]
Hi Chris, sorry for delay. It would be awesome if you just did just that, and then I'll take it over and get it on the front page :)

**Comment by lahwran** [comment]
Done!
